### ISSUE TITLE
값들 맞는지 test할  것

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/vba_collect_sales#21]
test방법은?

6개 브랜드 매출, 수량 맞는지 12개 시트 확인 할 것

각 시트별로 버튼 4개 잘 되는지, 서머리에 버튼 잘 되는지

*매크로가 계산한 값이 맞는지

**Comment by CHAEMEE** [comment]
-summary_채널별 _매출액 
 스토어팜 2번출력 -> 위탁사입수출구분 시트 스토어팜 중복제거. 
 간격오류발생. ->summary채널뿌리기 수정.
 폐쇄몰열에 합계출력 수정.
 합계구하기 출력간격오류 수정완료.

-summary_제품별 매출액 
 이상없음.

-브랜드_매출&_수량
 합계 오류.  ->md_engine.합계구하기 수정
 raw 데이터 시트에서 위탁사입수출컬럼에 값이 없는 경우 값이 출력 안됨.
따라서 합계값과 해당 행합계결과가 다름. ->raw 데이터 수정 필요.
