### ISSUE TITLE
채널 추가 이슈

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/vba_collect_sales#6]
다만, 채널의 경우에는 오름차순으로 할 시, 나중에 추가된 채널이 오름차순 기준으로 본래 데이터 사이에 훅 들어갈 수 있을 것 같은데요. 채널 추가의 경우 혼선이 없게 하려면 어떻게 하는 게 좋을까요?

**Comment by CHAEMEE** [comment]
dkdfsdf

**Comment by Kyeongrok** [comment]
test

**Comment by Kyeongrok** [comment]
채널 추가되거나 지워졌을 때 지운 후에 새로 그리면 업데이트 되도록 수정함
